baseURL = "https://brantlab.com"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "BrantLab IT"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/logo_only.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/brantlab.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Brantlab IT Consulting"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Your trusted consultant for the IT needs of your business"

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Brantlab"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = true

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false
    
    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = false

    [params.meta]
        keywords = "Brantlab IT Consulting, Van Wert, Ohio, IT Solutions by Brantlab, Convoy, Ohio, Brantlab Technology Services, Van Wert, OH, Professional IT Consultancy Brantlab, Convoy, OH, Brantlab Tech Advisors, IT Services Van Wert, Strategic IT Planning Brantlab, Convoy, Ohio, Brantlab Cybersecurity Solutions, Van Wert, OH, Cloud Computing with Brantlab, IT Consulting Convoy, Brantlab IT Support Services, Van Wert, Ohio, Brantlab Network Infrastructure, Convoy, OH, Managed IT Services Brantlab, Van Wert, Ohio, IT Consulting Experts Brantlab, Convoy, OH, Brantlab Data Security Solutions, IT Services Van Wert, Brantlab IT Outsourcing, Convoy, Ohio, Brantlab IT Strategy Consulting, Van Wert, OH, Brantlab Enterprise Solutions, IT Consulting Convoy, Brantlab IT Project Management, Van Wert, Ohio, Cutting-edge IT Solutions Brantlab, Convoy, OH, Brantlab IT Infrastructure Management, Van Wert, Ohio, Brantlab Digital Transformation Services, IT Services Convoy"

    [params.contact]
        email = "Contact@brantlab.com"
        phone = "Please email first"